Editor can select location
CraftAcademy/newsroom_staff-april-2020 pull request #15
Opened 2020-06-03 12:27 UTC by PaulineBA

## [PT LINK]( https://www.pivotaltracker.com/story/show/172888054 )
### User Story
```
As an editor
In order to give local news to the client
I would like to be able to associate the article with the location

```
## Screenshots (Client)
![Screen Shot 2020-06-03 at 2 26 18 PM](https://user-images.githubusercontent.com/62211126/83636423-3e80bd00-a5a6-11ea-92b1-0330ef62a0cb.png)

2020-06-03 13:06 UTC, erikbjoern commented on src/components/PublishArticle.jsx
> +          location: e.target.local.checked && "Sweden",
Looks clever. Have you checked with a debugger what param is sent off?

2020-06-03 13:12 UTC, designerofthing approved these changes

2020-06-03 13:18 UTC, erikbjoern requested changes
We need the form to be cleared when the editor has published the article

2020-06-03 13:19 UTC, erikbjoern commented on src/components/PublishArticle.jsx
> +          location: e.target.local.checked && "Sweden",
I checked now, in the local API log, we receive the param `location: "Sweden` 😎  Nice job!

2020-06-03 13:21 UTC, erikbjoern commented
Can you also add a fix for the Review layout? The image appears behind the 'published at' and the body, I guess that's because we increased the image size.

2020-06-03 16:51 UTC, kermit-klein approved these changes

2020-06-04 07:33 UTC, faraznaeem approved these changes

2020-06-05 12:10 UTC, ViaMarcus approved these changes

2020-06-05 23:00 UTC, kermit-klein commented
Can we merge this ?

2020-06-06 14:49 UTC, erikbjoern commented
Replaced by PR#16

2020-06-06 14:49 UTC, closed without merging